### ISSUE TITLE
Wrong header icon color after scrolling on dark mode

### ISSUE THREAD

**Issue by guilhermedeandrade** [moxystudio/react-native-with-moxy#46]
Just noticed that when using dark mode and after scrolling, the header icon that is rendered is the colorful one. It should probably be the white one, I guess. What do you think @satazor?

![image](https://user-images.githubusercontent.com/8797405/86354399-e69aac00-bc60-11ea-8e03-d6274fbe96e7.png)

**Comment by satazor** [comment]
Yep if that’s easy to fix I would do it. How is it in next with moxy?

**Comment by guilhermedeandrade** [comment]
It should be easy to fix and I'd already done a [similar fix on next-with-moxy](https://github.com/moxystudio/next-with-moxy/pull/52/files#diff-7b41b5af884eaeeacd9755ba9ba3fb3aR71). This issue is happening there as well.

Also, I can fix them. The only reason I didn't create a PR for this is because I would like to confirm how this logo should look.
