### ISSUE TITLE
Fix switch language button text

### ISSUE THREAD

**Issue by guilhermedeandrade** [moxystudio/react-native-with-moxy#54]
Initially the switch language button text says "Switch language (en-US)", but it should be ""Switch language (pt-PT)" instead.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/8797405/87920315-ed9f2800-ca70-11ea-926a-f9628c17c8c6.png">

**Comment by acostalima** [comment]
Closing. This is not really a critical issue in the scope of the boilerplate.
